### ISSUE TITLE
Camera Configuration Change is Slow

### ISSUE THREAD

**Issue by junjuew** [cmusatyalab/gabriel#14]
Current implementation close and reopens the camera to change the configuration. This is done to make sure devices that do not support configuration change on the fly (e.g. ODG R7) is still able to change the configuration. 

However, closing and reopening camera is slow (~second). For devices that support on-th-fly configuration change (e.g. nexus 6), it's better not to close and reopen the camera.

**Comment by rogerthat94** [comment]
Newer Gabriel clients ([example](https://github.com/cmusatyalab/activity-recognition-client)) will use Android's modern Camera packages (either Camera2 or CameraX).
