### ISSUE TITLE
Several 'Could not find file' at the opening of the legacy-hololens-client project.

### ISSUE THREAD

**Issue by simonlegrand** [cmusatyalab/gabriel#2]
Hello,

When I try to open the legacy-hololens-client project in Visual Studio, I have many failures saying that .cs files can't be found. Ex: [Failure] Could not find file 'C:\Users\slegrand\Downloads\gabriel-master\gabriel-master\client\legacy-hololens-client\gabriel-holo-client\Assets\HoloToolkit\Utilities\Scripts\NearPlaneFade.cs'.

I tried to use the HoloToolkit-Unity/Assets/Holotoolkit folder from https://github.com/Microsoft, I get less errors, but it seems that some files are still missing.

Do you have any idea how to solve this problem?

Regards,

Simon

**Comment by zhuoc** [comment]
Hi,

This part (the hololens client) is really a research project we are working on, so I'm sorry we haven't done much testing or documentation. It is possible that there are some files I should commit but I didn't - it's my first Unity+HoloLens project and I don't have an idea what should be in git...

So what files are missing after you have the library from Microsoft? Can you give an example?

Zhuo

**Comment by simonlegrand** [comment]
Hi Zhuo,

 Here is the list of what is missing after I add the HoloToolkit library:

Severity Code Description
Error CS2001 Source file '\\home-pro.rocq.inria.fr\
slegrand\Documents\SED\Willow\gabriel-master\gabriel-master\
client\legacy-hololens-client\gabriel-holo-client\Assets\
HoloToolkit\Sharing\Scripts\SDK\ImageTagLocationListener.cs' could not be
found.
Error CS2001 Source file '\\home-pro.rocq.inria.fr\
slegrand\Documents\SED\Willow\gabriel-master\gabriel-master\
client\legacy-hololens-client\gabriel-holo-client\Assets\
HoloToolkit\Sharing\Scripts\SDK\ImageTagLocationType.cs' could not be found.
Error CS2001 Source file '\\home-pro.rocq.inria.fr\
slegrand\Documents\SED\Willow\gabriel-master\gabriel-master\
client\legacy-hololens-client\gabriel-holo-client\Assets\
HoloToolkit\Sharing\Scripts\SDK\ImageTagManager.cs' could not be found.
Error CS2001 Source file '\\home-pro.rocq.inria.fr\
slegrand\Documents\SED\Willow\gabriel-master\gabriel-master\
client\legacy-hololens-client\gabriel-holo-client\Assets\
HoloToolkit\Input\Scripts\FocusedObjectMessageSender.cs' could not be found.
Error CS2001 Source file '\\home-pro.rocq.inria.fr\
slegrand\Documents\SED\Willow\gabriel-master\gabriel-master\
client\legacy-hololens-client\gabriel-holo-client\Assets\
HoloToolkit\Input\Scripts\BasicCursor.cs' could not be found.
Error CS2001 Source file '\\home-pro.rocq.inria.fr\
slegrand\Documents\SED\Willow\gabriel-master\gabriel-master\
client\legacy-hololens-client\gabriel-holo-client\Assets\
HoloToolkit\Input\Scripts\CursorFeedback.cs' could not be found.
Error CS2001 Source file '\\home-pro.rocq.inria.fr\
slegrand\Documents\SED\Willow\gabriel-master\gabriel-master\
client\legacy-hololens-client\gabriel-holo-client\Assets\
HoloToolkit\Input\Scripts\CursorManager.cs' could not be found.
Error CS2001 Source file '\\home-pro.rocq.inria.fr\
slegrand\Documents\SED\Willow\gabriel-master\gabriel-master\
client\legacy-hololens-client\gabriel-holo-client\Assets\
HoloToolkit\Input\Scripts\GazeManager.cs' could not be found.
Error CS2001 Source file '\\home-pro.rocq.inria.fr\
slegrand\Documents\SED\Willow\gabriel-master\gabriel-master\
client\legacy-hololens-client\gabriel-holo-client\Assets\
HoloToolkit\Input\Scripts\GestureManager.cs' could not be found.
Error CS2001 Source file '\\home-pro.rocq.inria.fr\
slegrand\Documents\SED\Willow\gabriel-master\gabriel-master\
client\legacy-hololens-client\gabriel-holo-client\Assets\
HoloToolkit\Input\Scripts\GazeStabilizer.cs' could not be found.
Error CS2001 Source file '\\home-pro.rocq.inria.fr\
slegrand\Documents\SED\Willow\gabriel-master\gabriel-master\
client\legacy-hololens-client\gabriel-holo-client\Assets\
HoloToolkit\Input\Scripts\GestureManipulator.cs' could not be found.
Error CS2001 Source file '\\home-pro.rocq.inria.fr\
slegrand\Documents\SED\Willow\gabriel-master\gabriel-master\
client\legacy-hololens-client\gabriel-holo-client\Assets\
HoloToolkit\Input\Scripts\OnSelectEvent.cs' could not be found.
Error CS2001 Source file '\\home-pro.rocq.inria.fr\
slegrand\Documents\SED\Willow\gabriel-master\gabriel-master\
client\legacy-hololens-client\gabriel-holo-client\Assets\
HoloToolkit\Input\Scripts\SelectedObjectMessageSender.cs' could not be
found.
Error CS2001 Source file '\\home-pro.rocq.inria.fr\
slegrand\Documents\SED\Willow\gabriel-master\gabriel-master\
client\legacy-hololens-client\gabriel-holo-client\Assets\
HoloToolkit\Input\Scripts\HandsManager.cs' could not be found.
Error CS2001 Source file '\\home-pro.rocq.inria.fr\
slegrand\Documents\SED\Willow\gabriel-master\gabriel-master\
client\legacy-hololens-client\gabriel-holo-client\Assets\
HoloToolkit\Input\Tests\Scripts\FocusedObjectMessageReceiver.cs' could not
be found.
Error CS2001 Source file '\\home-pro.rocq.inria.fr\
slegrand\Documents\SED\Willow\gabriel-master\gabriel-master\
client\legacy-hololens-client\gabriel-holo-client\Assets\
HoloToolkit\Input\Scripts\KeywordManager.cs' could not be found.
Error CS2001 Source file '\\home-pro.rocq.inria.fr\
slegrand\Documents\SED\Willow\gabriel-master\gabriel-master\
client\legacy-hololens-client\gabriel-holo-client\Assets\
HoloToolkit\Input\Scripts\OnGazeEnterEvent.cs' could not be found.
Error CS2001 Source file '\\home-pro.rocq.inria.fr\
slegrand\Documents\SED\Willow\gabriel-master\gabriel-master\
client\legacy-hololens-client\gabriel-holo-client\Assets\
HoloToolkit\Input\Scripts\OnGazeLeaveEvent.cs' could not be found.
Error CS2001 Source file '\\home-pro.rocq.inria.fr\
slegrand\Documents\SED\Willow\gabriel-master\gabriel-master\
client\legacy-hololens-client\gabriel-holo-client\Assets\
HoloToolkit\Sharing\Scripts\SDK\ImageTagLocation.cs' could not be found.
Error CS2001 Source file '\\home-pro.rocq.inria.fr\
slegrand\Documents\SED\Willow\gabriel-master\gabriel-master\
client\legacy-hololens-client\gabriel-holo-client\Assets\
HoloToolkit\Sharing\Scripts\SharingSessionTracker.cs' could not be found.
Error CS2001 Source file '\\home-pro.rocq.inria.fr\
slegrand\Documents\SED\Willow\gabriel-master\gabriel-master\
client\legacy-hololens-client\gabriel-holo-client\Assets\
HoloToolkit\Utilities\Scripts\ManualCameraControl.cs' could not be found.
Error CS2001 Source file '\\home-pro.rocq.inria.fr\
slegrand\Documents\SED\Willow\gabriel-master\gabriel-master\
client\legacy-hololens-client\gabriel-holo-client\Assets\
HoloToolkit\Utilities\Scripts\RollingStatistics.cs' could not be found.
Error CS2001 Source file '\\home-pro.rocq.inria.fr\
slegrand\Documents\SED\Willow\gabriel-master\gabriel-master\
client\legacy-hololens-client\gabriel-holo-client\Assets\
HoloToolkit\Utilities\Scripts\VectorExtensions.cs' could not be found.
Error CS2001 Source file '\\home-pro.rocq.inria.fr\
slegrand\Documents\SED\Willow\gabriel-master\gabriel-master\
client\legacy-hololens-client\gabriel-holo-client\Assets\
HoloToolkit\Utilities\Tests\TextToSpeechManagerTest.cs' could not be found.
Error CS2001 Source file '\\home-pro.rocq.inria.fr\
slegrand\Documents\SED\Willow\gabriel-master\gabriel-master\
client\legacy-hololens-client\gabriel-holo-client\Assets\
HoloToolkit\SpatialMapping\Tests\Support\PlaneFindingTest.cs' could not be
found.
Error CS2001 Source file '\\home-pro.rocq.inria.fr\
slegrand\Documents\SED\Willow\gabriel-master\gabriel-master\
client\legacy-hololens-client\gabriel-holo-client\Assets\
HoloToolkit\SpatialMapping\Tests\Support\SpatialProcessingTest.cs' could
not be found.


After I checked for some known problems related to these files, it seems
that some have been removed or replaced in the last version of the
HoloToolkit, like GestureManager.cs:
https://github.com/Microsoft/HoloToolkit-Unity/issues/431#issuecomment-269069595

Regards,

Simon

2017-01-20 23:12 GMT+01:00 Zhuo Chen <notifications@github.com>:

**Comment by jonathangranskog** [comment]
We're trying to test this project with HoloLens at work and from my first glance at the Unity project, it seems like you haven't enabled the "Force Text" option for Asset Serialization under Edit->Project Settings->Editor. You also need to commit all the .meta files. This should make Unity work properly with git. And it also seems like you didn't include any prefabs in the commit.

**Comment by rogerthat94** [comment]
You can find instructions to build the client (and all of the files that you need) [here](https://github.com/cmusatyalab/gabriel-instruction/tree/master/hololens). I didn't include HoloToolkit in that repository, because of copyright issues. But my instructions include steps to download it from Microsoft's repository and add it to the project.
