### ISSUE TITLE
No way to change the "engine_name" the android client is sending without rebuilding

### ISSUE THREAD

**Issue by junjuew** [cmusatyalab/gabriel#31]
Published Gabriel client app on Android play store has a [hard-coded "engine_name" of "instruction"](https://github.com/cmusatyalab/gabriel-instruction/blob/6c16480b5e92a23e6efd8c65d466f8070a21fd3a/android-client/app/src/main/java/edu/cmu/cs/gabrielclient/Const.java#L51). Currently, there doesn't seem to have an easy way to change this "engine_name" to something else without rebuilding a client APK.

This makes the android client rather specific for each individual application.

**Comment by rogerthat94** [comment]
The new Gabriel protocol uses `source_name` and `result_producer_name` fields. The `source_name` for the Gabriel Instruction client should always be `instruction`.
